package com.xforceplus.wapp.modules.check.entity;

import lombok.Getter;
import lombok.Setter;

/**
 * @author Bobby
 * @date 2018/4/23
 */
@Getter
@Setter
public final class InvoiceCheckMainModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.id
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private Long id;

    public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getPdfMd5() {
		return pdfMd5;
	}

	public void setPdfMd5(String pdfMd5) {
		this.pdfMd5 = pdfMd5;
	}

	public String getCyjgCode() {
		return cyjgCode;
	}

	public void setCyjgCode(String cyjgCode) {
		this.cyjgCode = cyjgCode;
	}

	public String getCyjgTip() {
		return cyjgTip;
	}

	public void setCyjgTip(String cyjgTip) {
		this.cyjgTip = cyjgTip;
	}

	public String getFpzl() {
		return fpzl;
	}

	public void setFpzl(String fpzl) {
		this.fpzl = fpzl;
	}

	public String getFpdm() {
		return fpdm;
	}

	public void setFpdm(String fpdm) {
		this.fpdm = fpdm;
	}

	public String getFphm() {
		return fphm;
	}

	public void setFphm(String fphm) {
		this.fphm = fphm;
	}

	public String getCycs() {
		return cycs;
	}

	public void setCycs(String cycs) {
		this.cycs = cycs;
	}

	public String getXfsh() {
		return xfsh;
	}

	public void setXfsh(String xfsh) {
		this.xfsh = xfsh;
	}

	public String getXfmc() {
		return xfmc;
	}

	public void setXfmc(String xfmc) {
		this.xfmc = xfmc;
	}

	public String getXfdzdh() {
		return xfdzdh;
	}

	public void setXfdzdh(String xfdzdh) {
		this.xfdzdh = xfdzdh;
	}

	public String getXfyhzh() {
		return xfyhzh;
	}

	public void setXfyhzh(String xfyhzh) {
		this.xfyhzh = xfyhzh;
	}

	public String getGfsh() {
		return gfsh;
	}

	public void setGfsh(String gfsh) {
		this.gfsh = gfsh;
	}

	public String getGfmc() {
		return gfmc;
	}

	public void setGfmc(String gfmc) {
		this.gfmc = gfmc;
	}

	public String getGfdzdh() {
		return gfdzdh;
	}

	public void setGfdzdh(String gfdzdh) {
		this.gfdzdh = gfdzdh;
	}

	public String getGfyhzh() {
		return gfyhzh;
	}

	public void setGfyhzh(String gfyhzh) {
		this.gfyhzh = gfyhzh;
	}

	public String getKprq() {
		return kprq;
	}

	public void setKprq(String kprq) {
		this.kprq = kprq;
	}

	public String getJe() {
		return je;
	}

	public void setJe(String je) {
		this.je = je;
	}

	public String getSe() {
		return se;
	}

	public void setSe(String se) {
		this.se = se;
	}

	public String getJshj() {
		return jshj;
	}

	public void setJshj(String jshj) {
		this.jshj = jshj;
	}

	public String getBz() {
		return bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	public String getJqbh() {
		return jqbh;
	}

	public void setJqbh(String jqbh) {
		this.jqbh = jqbh;
	}

	public String getKpr() {
		return kpr;
	}

	public void setKpr(String kpr) {
		this.kpr = kpr;
	}

	public String getSkr() {
		return skr;
	}

	public void setSkr(String skr) {
		this.skr = skr;
	}

	public String getFhr() {
		return fhr;
	}

	public void setFhr(String fhr) {
		this.fhr = fhr;
	}

	public String getLzfpdm() {
		return lzfpdm;
	}

	public void setLzfpdm(String lzfpdm) {
		this.lzfpdm = lzfpdm;
	}

	public String getLzfphm() {
		return lzfphm;
	}

	public void setLzfphm(String lzfphm) {
		this.lzfphm = lzfphm;
	}

	public String getZfbz() {
		return zfbz;
	}

	public void setZfbz(String zfbz) {
		this.zfbz = zfbz;
	}

	public String getUuid() {
		return uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public String getValid() {
		return valid;
	}

	public void setValid(String valid) {
		this.valid = valid;
	}

	public String getCreateDate() {
		return createDate;
	}

	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	public String getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(String updateDate) {
		this.updateDate = updateDate;
	}

	public String getCyrmc() {
		return cyrmc;
	}

	public void setCyrmc(String cyrmc) {
		this.cyrmc = cyrmc;
	}

	public String getCyrsbh() {
		return cyrsbh;
	}

	public void setCyrsbh(String cyrsbh) {
		this.cyrsbh = cyrsbh;
	}

	public String getSpfmc() {
		return spfmc;
	}

	public void setSpfmc(String spfmc) {
		this.spfmc = spfmc;
	}

	public String getSpfsbh() {
		return spfsbh;
	}

	public void setSpfsbh(String spfsbh) {
		this.spfsbh = spfsbh;
	}

	public String getShrmc() {
		return shrmc;
	}

	public void setShrmc(String shrmc) {
		this.shrmc = shrmc;
	}

	public String getShrsbh() {
		return shrsbh;
	}

	public void setShrsbh(String shrsbh) {
		this.shrsbh = shrsbh;
	}

	public String getFhrmc() {
		return fhrmc;
	}

	public void setFhrmc(String fhrmc) {
		this.fhrmc = fhrmc;
	}

	public String getFhrsbh() {
		return fhrsbh;
	}

	public void setFhrsbh(String fhrsbh) {
		this.fhrsbh = fhrsbh;
	}

	public String getQyd() {
		return qyd;
	}

	public void setQyd(String qyd) {
		this.qyd = qyd;
	}

	public String getYshwxx() {
		return yshwxx;
	}

	public void setYshwxx(String yshwxx) {
		this.yshwxx = yshwxx;
	}

	public String getCzch() {
		return czch;
	}

	public void setCzch(String czch) {
		this.czch = czch;
	}

	public String getCcdw() {
		return ccdw;
	}

	public void setCcdw(String ccdw) {
		this.ccdw = ccdw;
	}

	public String getSfzhm() {
		return sfzhm;
	}

	public void setSfzhm(String sfzhm) {
		this.sfzhm = sfzhm;
	}

	public String getCllx() {
		return cllx;
	}

	public void setCllx(String cllx) {
		this.cllx = cllx;
	}

	public String getCpxh() {
		return cpxh;
	}

	public void setCpxh(String cpxh) {
		this.cpxh = cpxh;
	}

	public String getCd() {
		return cd;
	}

	public void setCd(String cd) {
		this.cd = cd;
	}

	public String getHgzs() {
		return hgzs;
	}

	public void setHgzs(String hgzs) {
		this.hgzs = hgzs;
	}

	public String getJkzmsh() {
		return jkzmsh;
	}

	public void setJkzmsh(String jkzmsh) {
		this.jkzmsh = jkzmsh;
	}

	public String getSjdh() {
		return sjdh;
	}

	public void setSjdh(String sjdh) {
		this.sjdh = sjdh;
	}

	public String getFdjhm() {
		return fdjhm;
	}

	public void setFdjhm(String fdjhm) {
		this.fdjhm = fdjhm;
	}

	public String getCjhm() {
		return cjhm;
	}

	public void setCjhm(String cjhm) {
		this.cjhm = cjhm;
	}

	public String getSwjgdm() {
		return swjgdm;
	}

	public void setSwjgdm(String swjgdm) {
		this.swjgdm = swjgdm;
	}

	public String getSwjgmc() {
		return swjgmc;
	}

	public void setSwjgmc(String swjgmc) {
		this.swjgmc = swjgmc;
	}

	public String getWspzh() {
		return wspzh;
	}

	public void setWspzh(String wspzh) {
		this.wspzh = wspzh;
	}

	public String getDw() {
		return dw;
	}

	public void setDw(String dw) {
		this.dw = dw;
	}

	public String getXcrs() {
		return xcrs;
	}

	public void setXcrs(String xcrs) {
		this.xcrs = xcrs;
	}

	public String getSl() {
		return sl;
	}

	public void setSl(String sl) {
		this.sl = sl;
	}

	public String getJym() {
		return jym;
	}

	public void setJym(String jym) {
		this.jym = jym;
	}

	public String getTxfbz() {
		return txfbz;
	}

	public void setTxfbz(String txfbz) {
		this.txfbz = txfbz;
	}

	public String getLslbz() {
		return lslbz;
	}

	public void setLslbz(String lslbz) {
		this.lslbz = lslbz;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.PDF_MD5
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String pdfMd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.CYJG_CODE
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String cyjgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.CYJG_TIP
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String cyjgTip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.FPZL
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String fpzl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.FPDM
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String fpdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.FPHM
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String fphm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.CYCS
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String cycs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.XFSH
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String xfsh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.XFMC
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String xfmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.XFDZDH
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String xfdzdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.XFYHZH
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String xfyhzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.GFSH
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String gfsh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.GFMC
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String gfmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.GFDZDH
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String gfdzdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.GFYHZH
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String gfyhzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.KPRQ
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String kprq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.JE
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String je;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.SE
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String se;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.JSHJ
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String jshj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.BZ
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.JQBH
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String jqbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.KPR
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String kpr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.SKR
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String skr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.FHR
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String fhr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.LZFPDM
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String lzfpdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.LZFPHM
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String lzfphm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.ZFBZ
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String zfbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.uuid
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.valid
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.create_date
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.update_date
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.CYRMC
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String cyrmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.CYRSBH
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String cyrsbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.SPFMC
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String spfmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.SPFSBH
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String spfsbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.SHRMC
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String shrmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.SHRSBH
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String shrsbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.FHRMC
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String fhrmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.FHRSBH
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String fhrsbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.QYD
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String qyd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.YSHWXX
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String yshwxx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.CZCH
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String czch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.CCDW
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String ccdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.SFZHM
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String sfzhm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.CLLX
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String cllx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.CPXH
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String cpxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.CD
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String cd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.HGZS
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String hgzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.JKZMSH
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String jkzmsh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.SJDH
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String sjdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.FDJHM
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String fdjhm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.CJHM
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String cjhm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.SWJGDM
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String swjgdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.SWJGMC
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String swjgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.WSPZH
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String wspzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.DW
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String dw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.XCRS
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String xcrs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.SL
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String sl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.JYM
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String jym;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.TXFBZ
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String txfbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.LSLBZ
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String lslbz;
}
