# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
    max-http-post-size: -1
  port: 8080
  max-http-header-size: 16584
  servlet:
    context-path: /
spring:
  profiles:
    active: pro
  devtools:
    restart:
      #热部署生效
      enabled: false
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
  resources:
    static-locations: classpath:/static/,classpath:/views/,classpath:/excel/,classpath:/fonts/,classpath:/rauin_default_fonts/,classpath:/fapiao/
  servlet:
    multipart:
      max-file-size: 100MB
      location: /tmp/tomcat
      enabled: true
      max-request-size: 100MB
 
# Mybatis-Plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.xforceplus.wapp.repository.entity

# 日志
#logging:
#  path: /home/vn03qsx/logs/
#  file: ${logging.path}dxhy_jxpt

# 定时器配置
schedule:
  open: true  # 是否开启定时任务功能  true开启   false关闭

# token配置
token:
  expire_time: 18000 #过期时间，单位秒

# swagger配置
springfox:
  documentation:
    swagger-ui:
      base-url: /enhance-swagger
    swagger:
      v2:
        path: /enhance-swagger/v2/api-docs

#management配置
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: always