server:
  port: 6060
spring:
  redis:
    host: wapp-redis
    password: 
    port: 6379
    lettuce:
      pool:
        max-idle: 16
        max-action: 32
        min-idle: 8
  datasource:
    druid:
      url: jdbc:p6spy:sqlserver://10.100.20.5:1433;DatabaseName=testdb01
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      username: testuser01
      password: aGSsdsJFWd_w_1
      initial-size: 10
      max-active: 1000
      min-idle: 100
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      # testOnBorrow和testOnReturn在生产环境一般是不开启的，主要是性能考虑。失效连接主要通过testWhileIdle保证
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: false
        url-pattern: /druid/*
        login-username: admin
        login-password: admin456123
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
          enabled: true
        wall:
          config:
            multi-statement-allow: true
  activemq:
    broker-url: failover:(tcp://active-mq:61616)?randomize=false&jms.useAsyncSend=true&jms.sendTimeout=3000
    user: admin
    password: admin

# 税款所属期判断值
currentTaxPeriod: 15

# 注意事项, 上传到SFTP的数据请按照以下模板填充数据，要求
# 1、文件名可用由用户自己定义（务必全局唯一，对于重名的文件一律不处理）
# 2、电子表格名称如果需要自定义请通知研发配置（不需要发版）
# 3、电子表格表头（第一行）不允许变更，如果一定要变更请提前通知研发调整代码，重新发版
# 4、同一批单据和明细请按照模板格式统一存储到同一个excel的不同sheet中
# 5、SFTP路径定义如下
agreementBill:
  scan-cron: 0 0 4 * * ?
  parse-cron: 0 0 5 * * ?
  remote:
  # 协议单SFTP远程目录
    path: /home/wappftp/wapp/vendor/agreement
  local:
    path: /tmp/wapp/vendor/claim
  sheetName: fbl5n
  item:
    sheetName: zarr
claimBill:
  scan-cron: 0 0 22 * * ?
  parse-cron: 0 0 0 * * ?
  diff-amount-rate: -1
  remote:
# 索赔单及明细SFTP远程目录
    path: /home/wappftp/wapp/vendor/epd
  local:
    path: /tmp/wapp/vendor/claim
  sheetName: claim
  item:
    hyperSheetName: hyper
    samsSheetName: sams
epdBill:
  scan-cron: 0 30 4 * * ?
  parse-cron: 0 30 5 * * ?
  remote:
# EPD单及LOG明细SFTP远程目录
    path: /home/wappftp/wapp/vendor/epd
  local:
    path: /tmp/wapp/vendor/epd
  sheetName: epd
  item:
    sheetName: log
 
####索赔协议定时任务   
task: 
  AgreementDeductScheduler-cron: 0 0 4 * * ?
  ClaimBlueInvoiceScheduler-cron: 0 0 1 * * ?
  ClaimDeductScheduler-cron: 0 0 1 * * ?
  ClaimDeductTaxCodeScheduler-cron: 0 0 12 * * ?
  ClaimSettlementScheduler-cron:  0 0 3 * * ?
  EPDDeductScheduler-cron: 0 0 5 * * ?
  SettlementOverDueScheduler-cron: 0 0 1 * * ?
  SettlementScheduler-cron: 0 0 6 * * ?
  SettlementTaxCodeScheduler-cron: 0 0 20 * * ?
 
####################
#integration 集成平台相关配置
#################### 
wapp:
  integration:
    authentication: walmart-wapp-fat20211014092441131056839
    client-id: T3950544920211014092441131056783
    customer-no: T3950544920211014092441131056783
    tenant-id: 5793722992790675456
    tenant-code: Walmart
    tenant-name: Walmart
    action:
      # ofd解析 验签
      ofd: 0FBBB88B01E6EF8E84641AFA3521965F
      # 发票验真
      verification: E988114EC83E2C1FBA93F180B8D68CD8
      # xml解析
      verification-xml: 4BC83F3C4F4E95F7E3F6C599102A86FA
      # 申请红字信息表
      rednotification: C6D28535F2ADE4D5DB655AE71D87375A
      # 获取终端
      terminals: A9F0665B2C933F31D5145B7A1CC571EB
      splitInvoice: 9449D82ECF3D2712E47A489F491A19BD
      # 红字信息撤销
      rollback: E52D6CD30701F28988FBA92E1459AD45
      # 红字信息生成pdf
      genredpdf: 663133D11FC88FC56BA3585258005260
      #识别
      discern: 2C528F63F591A73C65007B9C16CF6E6F
      discern-callbackUrl: inte-janus.melete
      #下载附件
      downLoadAction: A9EC3ACD57C452AE933AE67B42E452E2
      # 税编查询
      tax-code: 88783DD6EF9484C5DB5EE795A0E920C1
      #上传3.0平台 税编
      send-tax-code: 77BC9129AC33F3F83DD73F2767BF2EF4
      #税编同步更新到3.0平台
      sync-tax-code: BF28FCB10A34719B7AC845DC561EF2EA
    host:
      tcp: janus-tcp-inte-tx.xforceplus.com
      http: https://janus-inte-tx.xforceplus.com:443
    sign:
      splitInvoice: 0618de7ca5a54e44b85293cc7929312e
      tax-code: 9afc34ea775683aa44fc1787da9bbeaf
      send-tax-code: 0618de7ca5a54e44b85293cc7929312e
    port:
      tcp: 443
    # riversand的税编同步接口地址-生产
  host:
    # MB
    buffer-size: 4
    base-url: https://aloha-qa.walmartmobile.cn
    c-name: wapp-evat
    app-name: chc-fapiao
    app-access-token: 70F7DAEB1555DE8DC9D47746ABF22195
    # riversand的税编同步接口地址-生产
    tax-code-url: /item-oe/riversand/export/v1/page/info
    hyper-nbrs-url: /item-oe/db2Direct/findByUpcNumbers
    sams-nbrs-url: /item-oe/riversand/export/v1/info
  export_success_queue_gfone: cn.wm.host.export.success.queue.gfone
  export:
    tmp: /tmp/excel
  rednotification:
    maxApply: 50
  history-data:
    time: 2022-10-31 17:00:00   
  tax-rate: 0.00,0.01,0.03,0.06,0.09,0.10,0.11,0.13,0.16,0.17
  nas:
    url: /evtaSystemIntegration/wapp
    
#ESB    
Esb:
  url:
    upload: http://10.100.2.17:8083/object/upload
    downLoad: http://10.100.2.17:8083/object/downLoad/   
##
##
##消息队列相关配置
activemq:
  queue-name:
    export-request: cn.wm.host.enhance.export-request.queue # 导出申请
    enhance-claim-verdict-queue: cn.wm.host.enhance.claim.verdict.queue #索赔单不定案逻辑处理
    export-success-queue-gfone: cn.wm.host.export.success.queue.gfone
    deduct-notification: cn.wm.host.enhance.deduct.notification.queue
    import-riversand-taxcode-queue: import.riverand.taxcode.queque #riversand税编导入比较逻辑处理
taxRateSet: 0.13,0.11,0.09,0.06,0.05,0.03,0.01,0.00

####sftp配置
pro:
  sftp:
    host: sftp-chart  #10.44.100.123
    username: wappftp
    password: testwapp123
    # 授权方式：公私钥和密码选择一个，测试时选择密码,pwd密码，private 私钥，默认private
    auth-method: pwd
    default:
      port: 22
      timeout: 60000
      privateKey: /home/wappftp/.ssh/id_rsa
      passphrase:
#
#SFTP 定义路径
#图片存储路径
filePathConstan:
  remoteImageRootPath: /home/wappftp/jxfp/image/
  remoteCostFileRootPath: /home/wappftp/jxfp/cost/
  remoteKnowFileRootPath: /home/wappftp/jxfp/knowCenter/
  remoteAnnouncementRootPath: /home/wappftp/jxfp/announcement/
  remoteQuestionPaperFileRootPath: /home/wappftp/jxfp/question/
  remoteQuestionPaperFileTempRootPath: /home/wappftp/jxfp/temp/question/
  remoteCostFileTempRootPath: /home/wappftp/jxfp/temp/cost/
  remoteExcelFileRootPath: /home/wappftp/wapp/excel/
  remoteFixedRootPath: /jxfp/fixed/ #供应商红票remoteFixedRootPath
  remoteFixedTempRootPath: /jxfp/temp/fixed/ #供应商红票远程文件临时存放路径
  localImageRootPath: /home/vn03qsx/jxfp/image/
  tempPath: /home/wappftp/jxfp/temp/zip/      # 文件暂存路径
  depositPath: /home/wappftp/jxfp/zipto/ # 文件存储路
  tempImgPath: /home/wappftp/jxfp/temp/imgzip/      # 图片临时存储路径
  signInImgPath: /home/wappftp/jxfp/temp/image/     #扫码签收图片暂存路径
  tempDir: /home/wappftp/jxfp/temp/excelZip/
  sapRemoteRootPath: /jxfp/sap/source/   #sap源文件目录
  sapRemoteBakPath: /jxfp/sap/bak/       #sap备份目录
  sapLocalTempPath: /home/wappftp/jxfp/sap/temp/         #sap本地临时目录
  aribatempPath: /usr/users/dxhy152/wapp/jxfp/temp/zip/      # 文件暂存路径
  aribadepositPath: /usr/users/dxhy152/wapp/jxfp/zipto/ # 文件存储路
  erweimaPath: /usr/users/dxhy152/wapp/jxfp/QRCode/image/
  orderSapRemoteRootPath: /jxfp/order/sap/source/   #sap源文件目录（订单获取）
  orderSapRemoteBakPath: /jxfp/order/sap/bak/       #sap备份目录（订单获取）
  orderSapLocalTempPath: /usr/users/dxhy152/wapp/jxfp/order/sap/temp/
  vendorRemoteRootPath: /jxfp/vendor/source/   #vendor源文件目录(导入10位供应商号)
  vendorRemoteBakPath: /jxfp/vendor/bak/       #vendor备份目录
  vendorLocalTempPath: /usr/users/dxhy152/wapp/jxfp/vendor/temp/         #vendor本地临时目录
  localFixedRootPath: /usr/users/dxhy152/wapp/jxfp/fixed/temp/ #供应商红票本地文件存放路径
  sso: d:/sso/sso.txt


#定时删除原始数据
del-origin-data-timer:
  open: true
  beforeDays: 2
  handle-cron: 0 0 12 * * ?
  
#riverSand定时任务
riverSand:
  synchro-cron: 0 0 5 * 11 7
  latestTime: 2015-01-01 00:00:00
host:
  synchro-cron: 0 16 3 * * 1
  login-name: gf001,gf002,j0j0h4w,l5feng,m0w0aus,s0c07id,vdeng,vn52fx3,a0p00ug
  
#####chc 限制红字开票税盘
taxNo:
  terminal: {"914403007109368585":"RCNFMZ4U,BQFHFLGG,IH9HPG12"}

###BMS配置信息
bms:
  feedback:
    # 加密秘钥
    appSecret: 9039965DEA73EF189935D9044EC08AC6
    # bms验真结果反馈
    bmsVerifyFeedbackUrl: https://mdc-qa-aloha-gateway.cn.wal-mart.com/bms-cost/wapp/in/feedback/invoice
    bmsTaxBillFeedbackUrl: https://mdc-qa-aloha-gateway.cn.wal-mart.com/bms-cost/wapp/in/feedback/taxBill
    bmsQueryTaxBillUrl: https://mdc-qa-aloha-gateway.cn.wal-mart.com/bms-cost/wapp/in/queryTaxBill
    bmsInvoiceReceiptUrl: https://mdc-qa-aloha-gateway.cn.wal-mart.com/bms-cost/wapp/in/feedback/invoiceReceipt