spring:
  datasource:
    url: jdbc:sqlserver://161.163.58.63:14481;DatabaseName=WAPP
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: svcwappdb
    password: fwtmhqgSaT9RSPIB
    initial-size: 10
    min-idle: 100
    max-active: 20
    test-on-borrow: true
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-While-Idle: true
    test-on-return: false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall,log4j,config
