# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 80
    context-path: /b2bportal/dxhy-gylpt

# mysql
spring:
    devtools:
            restart:
                #热部署生效
              enabled: true
    # 环境 dev|test|pro|fast|mycat
    profiles:
        active: test
    # jackson时间格式化
    jackson:
        time-zone: GMT+0
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    # 指定静态资源的路径
    resources:
        static-locations: classpath:/static/,classpath:/views/
    redis:
        open: false  # 是否开启redis缓存  true开启   false关闭
        database: 0
        host: localhost
        port: 16379
        password:       # 密码（默认为空）
        timeout: 6000  # 连接超时时长（毫秒）
        pool:
            max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
            max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-idle: 10      # 连接池中的最大空闲连接
            min-idle: 5       # 连接池中的最小空闲连接
    # Activemq
    
activemq:
      url: failover:(tcp://tstr501218.cn.wal-mart.com:61616\,tcp://tstr501219.cn.wal-mart.com:61616)?randomize=false&jms.useAsyncSend=true&jms.sendTimeout=3000
      url_one: tcp://tstr501218.cn.wal-mart.com:61616
      url_two: tcp://tstr501219.cn.wal-mart.com:61616
      user: system
      password: manager
      queue: cn.wm.host.invoice_test.request
      queueResponse: cn.wm.host.invoice_test.response

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    configLocation: classpath:mybatis.xml

# 日志
logging:
  path: /home/vn088jh/logs/
  file: ${logging.path}dxhy_jxpt

# 定时器配置
schedule:
    open: false  # 是否开启定时任务功能  true开启   false关闭

#图片存储路径
filePathConstan:
    localImageRootPath: /home/vn088jh/jxfp/image/
    remoteImageRootPath: /wapp/jxfp/image/
    remoteCostFileRootPath: /wapp/jxfp/cost/
    remoteKnowFileRootPath: /wapp/jxfp/knowCenter/
    remoteAnnouncementRootPath: /wapp/jxfp/announcement/
    remoteQuestionPaperFileRootPath: /wapp/jxfp/question/
    remoteQuestionPaperFileTempRootPath: /wapp/jxfp/temp/question/
    remoteCostFileTempRootPath: /wapp/jxfp/temp/cost/
    tempPath: /home/vn088jh/jxfp/temp/zip/      # 文件暂存路径
    depositPath: /home/vn088jh/jxfp/zipto/ # 文件存储路
    tempImgPath: /home/vn088jh/jxfp/temp/imgzip/      # 图片临时存储路径
    signInImgPath: /home/vn088jh/jxfp/temp/image/     #扫码签收图片暂存路径
    tempDir: /home/vn088jh/jxfp/temp/excelZip/
    sapRemoteRootPath: /wapp/jxfp/sap/source/   #sap源文件目录
    sapRemoteBakPath: /wapp/jxfp/sap/bak/       #sap备份目录
    sapLocalTempPath: /home/vn088jh/jxfp/sap/temp/         #sap本地临时目录
    erweimaPath: /home/vn088jh/jxfp/QRCode/image/

#sftp配置

pro:
  sftp:
    host: 10.233.50.23  #10.44.100.123
    username: vn088jh
    password: Dxhy@2018!
    default:
      port: 22
      timeout: 60000
# Mycat配置
mycat:
    default_schema_label: db_210  # 默认的分库schema名称

# token配置
token:
    expire_time: 18000 #过期时间，单位秒

# 税款所属期判断值
currentTaxPeriod: 15
#扫描修改处理
scanEditUrl: http://127.0.0.1:8385/dxhy_yxgl_api/onlineUpload/updateInvoice

