package com.xforceplus.wapp.modules.check.entity;

import lombok.Getter;
import lombok.Setter;

/**
 * @author Bobby
 * @date 2018/4/24
 * 查验详情
 */
@Getter
@Setter
public final class InvoiceCheckDetailModel {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice_detail.id
     *
     * @mbggenerated Tue Apr 24 10:41:57 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice_detail.uuid
     *
     * @mbggenerated Tue Apr 24 10:41:57 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice_detail.detail_no
     *
     * @mbggenerated Tue Apr 24 10:41:57 CST 2018
     */
    private String detailNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice_detail.goods_name
     *
     * @mbggenerated Tue Apr 24 10:41:57 CST 2018
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice_detail.model
     *
     * @mbggenerated Tue Apr 24 10:41:57 CST 2018
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice_detail.unit
     *
     * @mbggenerated Tue Apr 24 10:41:57 CST 2018
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice_detail.num
     *
     * @mbggenerated Tue Apr 24 10:41:57 CST 2018
     */
    private String num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice_detail.unit_price
     *
     * @mbggenerated Tue Apr 24 10:41:57 CST 2018
     */
    private String unitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice_detail.detail_amount
     *
     * @mbggenerated Tue Apr 24 10:41:57 CST 2018
     */
    private String detailAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice_detail.tax_rate
     *
     * @mbggenerated Tue Apr 24 10:41:57 CST 2018
     */
    private String taxRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice_detail.tax_amount
     *
     * @mbggenerated Tue Apr 24 10:41:57 CST 2018
     */
    private String taxAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice_detail.cph
     *
     * @mbggenerated Tue Apr 24 10:41:57 CST 2018
     */
    private String cph;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice_detail.lx
     *
     * @mbggenerated Tue Apr 24 10:41:57 CST 2018
     */
    private String lx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice_detail.txrqq
     *
     * @mbggenerated Tue Apr 24 10:41:57 CST 2018
     */
    private String txrqq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice_detail.txrqz
     *
     * @mbggenerated Tue Apr 24 10:41:57 CST 2018
     */
    private String txrqz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice_detail.goods_num
     *
     * @mbggenerated Tue Apr 24 10:41:57 CST 2018
     */
    private String goodsNum;

}
