package com.xforceplus.wapp.modules.check.entity;

import lombok.Getter;
import lombok.Setter;

/**
 * @author Bobby
 * @date 2018/4/23
 */
@Getter
@Setter
public final class InvoiceCheckMainModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.id
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.PDF_MD5
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String pdfMd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.CYJG_CODE
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String cyjgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.CYJG_TIP
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String cyjgTip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.FPZL
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String fpzl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.FPDM
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String fpdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.FPHM
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String fphm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.CYCS
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String cycs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.XFSH
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String xfsh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.XFMC
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String xfmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.XFDZDH
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String xfdzdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.XFYHZH
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String xfyhzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.GFSH
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String gfsh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.GFMC
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String gfmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.GFDZDH
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String gfdzdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.GFYHZH
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String gfyhzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.KPRQ
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String kprq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.JE
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String je;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.SE
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String se;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.JSHJ
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String jshj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.BZ
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.JQBH
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String jqbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.KPR
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String kpr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.SKR
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String skr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.FHR
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String fhr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.LZFPDM
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String lzfpdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.LZFPHM
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String lzfphm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.ZFBZ
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String zfbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.uuid
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.valid
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.create_date
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.update_date
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.CYRMC
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String cyrmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.CYRSBH
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String cyrsbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.SPFMC
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String spfmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.SPFSBH
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String spfsbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.SHRMC
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String shrmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.SHRSBH
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String shrsbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.FHRMC
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String fhrmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.FHRSBH
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String fhrsbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.QYD
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String qyd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.YSHWXX
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String yshwxx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.CZCH
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String czch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.CCDW
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String ccdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.SFZHM
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String sfzhm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.CLLX
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String cllx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.CPXH
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String cpxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.CD
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String cd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.HGZS
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String hgzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.JKZMSH
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String jkzmsh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.SJDH
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String sjdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.FDJHM
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String fdjhm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.CJHM
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String cjhm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.SWJGDM
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String swjgdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.SWJGMC
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String swjgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.WSPZH
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String wspzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.DW
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String dw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.XCRS
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String xcrs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.SL
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String sl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.JYM
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String jym;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.TXFBZ
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String txfbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice.LSLBZ
     *
     * @mbggenerated Mon Apr 23 17:54:33 CST 2018
     */
    private String lslbz;
}
