package com.xforceplus.wapp.modules.check.entity;

import lombok.Getter;
import lombok.Setter;

/**
 * @author Bobby
 * @date 2018/4/24
 */
@Getter
@Setter
public class InvoiceCheckVehicleDetailModel {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.id
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.uuid
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.buyer_id_num
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String buyerIdNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.vehicle_type
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String vehicleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.factory_model
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String factoryModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.product_place
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String productPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.certificate
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String certificate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.certificate_import
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String certificateImport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.inspection_num
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String inspectionNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.engine_no
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String engineNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.vehicle_no
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String vehicleNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.phone
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.buyer_bank
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String buyerBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.tax_rate
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String taxRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.tax_bureau_name
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String taxBureauName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.tax_bureau_code
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String taxBureauCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.tax_records
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String taxRecords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.limit_people
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String limitPeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.check_status
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String checkStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.tonnage
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String tonnage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.create_date
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String createDate;
}
