package com.xforceplus.wapp.modules.check.entity;

import lombok.Getter;
import lombok.Setter;

/**
 * @author Bobby
 * @date 2018/4/24
 * 查验详情
 */
@Getter
@Setter
public final class InvoiceCheckDetailModel {

    public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUuid() {
		return uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public String getDetailNo() {
		return detailNo;
	}

	public void setDetailNo(String detailNo) {
		this.detailNo = detailNo;
	}

	public String getGoodsName() {
		return goodsName;
	}

	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName;
	}

	public String getModel() {
		return model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String getUnit() {
		return unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public String getNum() {
		return num;
	}

	public void setNum(String num) {
		this.num = num;
	}

	public String getUnitPrice() {
		return unitPrice;
	}

	public void setUnitPrice(String unitPrice) {
		this.unitPrice = unitPrice;
	}

	public String getDetailAmount() {
		return detailAmount;
	}

	public void setDetailAmount(String detailAmount) {
		this.detailAmount = detailAmount;
	}

	public String getTaxRate() {
		return taxRate;
	}

	public void setTaxRate(String taxRate) {
		this.taxRate = taxRate;
	}

	public String getTaxAmount() {
		return taxAmount;
	}

	public void setTaxAmount(String taxAmount) {
		this.taxAmount = taxAmount;
	}

	public String getCph() {
		return cph;
	}

	public void setCph(String cph) {
		this.cph = cph;
	}

	public String getLx() {
		return lx;
	}

	public void setLx(String lx) {
		this.lx = lx;
	}

	public String getTxrqq() {
		return txrqq;
	}

	public void setTxrqq(String txrqq) {
		this.txrqq = txrqq;
	}

	public String getTxrqz() {
		return txrqz;
	}

	public void setTxrqz(String txrqz) {
		this.txrqz = txrqz;
	}

	public String getGoodsNum() {
		return goodsNum;
	}

	public void setGoodsNum(String goodsNum) {
		this.goodsNum = goodsNum;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice_detail.id
     *
     * @mbggenerated Tue Apr 24 10:41:57 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice_detail.uuid
     *
     * @mbggenerated Tue Apr 24 10:41:57 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice_detail.detail_no
     *
     * @mbggenerated Tue Apr 24 10:41:57 CST 2018
     */
    private String detailNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice_detail.goods_name
     *
     * @mbggenerated Tue Apr 24 10:41:57 CST 2018
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice_detail.model
     *
     * @mbggenerated Tue Apr 24 10:41:57 CST 2018
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice_detail.unit
     *
     * @mbggenerated Tue Apr 24 10:41:57 CST 2018
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice_detail.num
     *
     * @mbggenerated Tue Apr 24 10:41:57 CST 2018
     */
    private String num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice_detail.unit_price
     *
     * @mbggenerated Tue Apr 24 10:41:57 CST 2018
     */
    private String unitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice_detail.detail_amount
     *
     * @mbggenerated Tue Apr 24 10:41:57 CST 2018
     */
    private String detailAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice_detail.tax_rate
     *
     * @mbggenerated Tue Apr 24 10:41:57 CST 2018
     */
    private String taxRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice_detail.tax_amount
     *
     * @mbggenerated Tue Apr 24 10:41:57 CST 2018
     */
    private String taxAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice_detail.cph
     *
     * @mbggenerated Tue Apr 24 10:41:57 CST 2018
     */
    private String cph;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice_detail.lx
     *
     * @mbggenerated Tue Apr 24 10:41:57 CST 2018
     */
    private String lx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice_detail.txrqq
     *
     * @mbggenerated Tue Apr 24 10:41:57 CST 2018
     */
    private String txrqq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice_detail.txrqz
     *
     * @mbggenerated Tue Apr 24 10:41:57 CST 2018
     */
    private String txrqz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_record_invoice_detail.goods_num
     *
     * @mbggenerated Tue Apr 24 10:41:57 CST 2018
     */
    private String goodsNum;

}
