package com.xforceplus.wapp.modules.check.entity;

import lombok.Getter;
import lombok.Setter;

/**
 * @author Bobby
 * @date 2018/4/24
 */
@Getter
@Setter
public class InvoiceCheckVehicleDetailModel {

    public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUuid() {
		return uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public String getBuyerIdNum() {
		return buyerIdNum;
	}

	public void setBuyerIdNum(String buyerIdNum) {
		this.buyerIdNum = buyerIdNum;
	}

	public String getVehicleType() {
		return vehicleType;
	}

	public void setVehicleType(String vehicleType) {
		this.vehicleType = vehicleType;
	}

	public String getFactoryModel() {
		return factoryModel;
	}

	public void setFactoryModel(String factoryModel) {
		this.factoryModel = factoryModel;
	}

	public String getProductPlace() {
		return productPlace;
	}

	public void setProductPlace(String productPlace) {
		this.productPlace = productPlace;
	}

	public String getCertificate() {
		return certificate;
	}

	public void setCertificate(String certificate) {
		this.certificate = certificate;
	}

	public String getCertificateImport() {
		return certificateImport;
	}

	public void setCertificateImport(String certificateImport) {
		this.certificateImport = certificateImport;
	}

	public String getInspectionNum() {
		return inspectionNum;
	}

	public void setInspectionNum(String inspectionNum) {
		this.inspectionNum = inspectionNum;
	}

	public String getEngineNo() {
		return engineNo;
	}

	public void setEngineNo(String engineNo) {
		this.engineNo = engineNo;
	}

	public String getVehicleNo() {
		return vehicleNo;
	}

	public void setVehicleNo(String vehicleNo) {
		this.vehicleNo = vehicleNo;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getBuyerBank() {
		return buyerBank;
	}

	public void setBuyerBank(String buyerBank) {
		this.buyerBank = buyerBank;
	}

	public String getTaxRate() {
		return taxRate;
	}

	public void setTaxRate(String taxRate) {
		this.taxRate = taxRate;
	}

	public String getTaxBureauName() {
		return taxBureauName;
	}

	public void setTaxBureauName(String taxBureauName) {
		this.taxBureauName = taxBureauName;
	}

	public String getTaxBureauCode() {
		return taxBureauCode;
	}

	public void setTaxBureauCode(String taxBureauCode) {
		this.taxBureauCode = taxBureauCode;
	}

	public String getTaxRecords() {
		return taxRecords;
	}

	public void setTaxRecords(String taxRecords) {
		this.taxRecords = taxRecords;
	}

	public String getLimitPeople() {
		return limitPeople;
	}

	public void setLimitPeople(String limitPeople) {
		this.limitPeople = limitPeople;
	}

	public String getCheckStatus() {
		return checkStatus;
	}

	public void setCheckStatus(String checkStatus) {
		this.checkStatus = checkStatus;
	}

	public String getTonnage() {
		return tonnage;
	}

	public void setTonnage(String tonnage) {
		this.tonnage = tonnage;
	}

	public String getCreateDate() {
		return createDate;
	}

	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.id
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.uuid
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.buyer_id_num
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String buyerIdNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.vehicle_type
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String vehicleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.factory_model
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String factoryModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.product_place
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String productPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.certificate
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String certificate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.certificate_import
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String certificateImport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.inspection_num
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String inspectionNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.engine_no
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String engineNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.vehicle_no
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String vehicleNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.phone
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.buyer_bank
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String buyerBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.tax_rate
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String taxRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.tax_bureau_name
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String taxBureauName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.tax_bureau_code
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String taxBureauCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.tax_records
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String taxRecords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.limit_people
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String limitPeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.check_status
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String checkStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.tonnage
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String tonnage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dx_check_vehicle_sale_invoice.create_date
     *
     * @mbggenerated Tue Apr 24 11:41:39 CST 2018
     */
    private String createDate;
}
