spring:
  redis:
    cluster: 
      nodes: ltst-redis-app-500745-mdc.cn.wal-mart.com:6379,ltst-redis-app-500746-mdc.cn.wal-mart.com:6379,ltst-redis-app-500747-mdc.cn.wal-mart.com:6379,ltst-redis-app-500748-mdc.cn.wal-mart.com:6379,ltst-redis-app-500749-mdc.cn.wal-mart.com:6379,ltst-redis-app-500750-mdc.cn.wal-mart.com:6379 
    password: redis(qa)
    port: 6379
    lettuce:
      pool:
        max-idle: 16
        max-action: 32
        min-idle: 8
  datasource:
    druid:
      url: jdbc:sqlserver://10.233.50.22:1433;DatabaseName=wwapp
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      username: svcacctwwapp
      password: 9RMI4dMyr1uZvths
      initial-size: 10
      max-active: 1000
      min-idle: 100
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      # testOnBorrow和testOnReturn在生产环境一般是不开启的，主要是性能考虑。失效连接主要通过testWhileIdle保证
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin456123
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
          enabled: true
        wall:
          config:
            multi-statement-allow: true
  activemq:
    broker-url: tcp://10.233.50.33:61616
    user: user
    password: user
    
# 税款所属期判断值
currentTaxPeriod: 15

# 注意事项, 上传到SFTP的数据请按照以下模板填充数据，要求
# 1、文件名可用由用户自己定义（务必全局唯一，对于重名的文件一律不处理）
# 2、电子表格名称如果需要自定义请通知研发配置（不需要发版）
# 3、电子表格表头（第一行）不允许变更，如果一定要变更请提前通知研发调整代码，重新发版
# 4、同一批单据和明细请按照模板格式统一存储到同一个excel的不同sheet中
# 5、SFTP路径定义如下
agreementBill:
  scan-cron: 0 0 0/1 * * ?
  parse-cron: 0 5 0/1 * * ?
  remote:
# 协议单SFTP远程目录
    path: /wapp/vendor/agreement
  local:
    path: /tmp/wapp/vendor/agreement
  sheetName: fbl5n
  item:
    sheetName: zarr
claimBill:
  scan-cron: 0 0 23 * * ?
  parse-cron: 0 0 0 * * ?
  diff-amount-rate: -1
  remote:
# 索赔单及明细SFTP远程目录
    path: /wapp/vendor/claim
  local:
    path: /tmp/wapp/vendor/claim
  sheetName: claim
  item:
    hyperSheetName: hyper
    samsSheetName: sams
epdBill:
  scan-cron: 0 0 23 * * ?
  parse-cron: 0 0 0 * * ?
  remote:
# EPD单及LOG明细SFTP远程目录
    path: /wapp/vendor/epd
  local:
    path: /tmp/wapp/vendor/epd
  sheetName: epd
  item:
    sheetName: log
    
####索赔协议定时任务   
task: 
  AgreementDeductScheduler-cron: 0 0 4 * * ?
  ClaimBlueInvoiceScheduler-cron: 0 0 1 * * ?
  ClaimDeductScheduler-cron: 0 0 1 * * ?
  ClaimDeductTaxCodeScheduler-cron: 0 0 12 * * ?
  ClaimSettlementScheduler-cron:  0 0 3 * * ?
  EPDDeductScheduler-cron: 0 0 5 * * ?
  SettlementOverDueScheduler-cron: 0 0 1 * * ?
  SettlementScheduler-cron: 0 0 6 * * ?
  SettlementTaxCodeScheduler-cron: 0 0 20 * * ?
  blueInvoiceAutoAuth-cron: 0 0 1 * * ?
  RedNotificationScheduler-cron: 0 10/10 * * * ?
  RedNotificationAutoApplyScheduler-cron: 0 0/5 * * * ?
  SysLogClearExpireScheduler-cron: 0 0 2 * * ?
  customerBMS-cron: 0 0/10 * * * ?
  InvoiceReceiptBMS-cron: 0 0/30 * * * ?
 
    
####################
#integration 集成平台相关配置
#################### 
wapp:
  integration:
    authentication: awtwal20211021163808132734345
    authentication-split: awtwal20211021163808132734345
    client-id: T3950544920211021163808132734293
    customer-no: T3950544920211021163808132734293
    tenant-id: 5793722992790675456
    tenant-code: Walmart
    tenant-name: Walmart
    action:
      # ofd解析 验签
      ofd: 99CEBE6F377F1AA9A06630156089B5DC
      # 发票验真
      verification: B39C8FC6A401DD9C721673E9F59107CE
      # 申请红字信息表
      rednotification: BCD13FE603B5978CFD1F22B0CDF8E844
      # 获取终端
      terminals: FDBA5816F16F7370D028A3BBA19095EC
      splitInvoice: 9313B7B33B8F4AEDD901B14471D2921A
      # 红字信息撤销
      rollback: AA74CE04064CC888C0CCE714D806653F
      # 红字信息生成pdf
      genredpdf: 0893F68B9DC49C547248D1B6353EE113
      #识别
      discern: 38DC49E8BDAF6CD52D6101856D3EAA0C
      #下载附件
      downLoadAction: DBD265D0D5405DE2732C8961CB9DFA32
      discern-callbackUrl: inte-janus.melete
      # 税编查询
      tax-code: B3442336397061B0307DEF1C8CEC9D1F
      #上传3.0平台 税编
      send-tax-code: FEB0D127FE34F9A4B3355BB1FAEBF5F5
      #税编同步更新到3.0平台
      sync-tax-code: 8D515114A1ED565849FA01B1D2B24D15
      #XML解析
      verification-xml: B0866628069E8ED01F319F3AE36A111B
    host:
      tcp: janus-tcp-inte-tx.xforceplus.com
      http: https://janus-inte-tx.xforceplus.com
    sign:
      tax-code: 8017ff73c2010e6a783394833e7ec92a
      splitInvoice: 8017ff73c2010e6a783394833e7ec92a
      send-tax-code: 0618de7ca5a54e44b85293cc7929312e
    port:
      tcp: 443
    # riversand的税编同步接口地址-生产
    riversand:
      url: http://esb-qa.cn.wal-mart.com/ssp-item-oe/riversand/export/v1/page/info
  db2:
    base-url: https://aloha-qa.walmartmobile.cn
  export:
      tmp: E:/tomcattmp
  rednotification:
    maxApply: 99
  host:
    base-url: http://esb-qa.cn.wal-mart.com
    c-name: wapp-evat
    app-name: chc-fapiao
    bufferSize: 4
    app-access-token: 70F7DAEB1555DE8DC9D47746ABF22195
    # riversand的税编同步接口地址-生产
    tax-code-url: /item-oe/riversand/export/v1/page/info
    hyper-nbrs-url: /item-oe/db2Direct/findByUpcNumbers
    sams-nbrs-url: /item-oe/riversand/export/v1/info
  history-data:
    time: 2022-10-31 17:00:00
  tax-rate: 0.00,0.01,0.03,0.06,0.09,0.10,0.11,0.13,0.16,0.17
  nas:
    url: /u/app/evtaSystemIntegration/wapp

#ESB
Esb:
  url:
    upload: http://10.100.2.17:8083/object/upload
    downLoad: http://10.100.2.17:8083/object/downLoad/
 
##
##
##消息队列相关配置 
activemq:
  queue-name:
    export-request: cn.wm.host.enhance.export-request.queue # 导出申请
    enhance-claim-verdict-queue: cn.wm.host.enhance.claim.verdict.queue #索赔单不定案逻辑处理
    export-success-queue-gfone: cn.wm.host.export.success.queue.gfone
    deduct-notification: fat-cn.wm.host.enhance.deduct.notification.queue
    import-riversand-taxcode-queue: import.riverand.taxcode.queque #riversand税编导入比较逻辑处理
taxRateSet: 0.13,0.11,0.09,0.06,0.05,0.03,0.01,0.00

####sftp配置
pro:
  sftp:
    host: 10.233.50.23    #10.233.50.33  #10.44.100.123
    username: SVCwappvm
    password: 
    # 授权方式：公私钥和密码选择一个，测试时选择密码,pwd密码，private 私钥，默认private
#    auth-method: pwd
    default:
      port: 22
      timeout: 60000

      privateKey: /u/app/ssh/id_rsa
      passphrase:

#
#SFTP 定义路径
#图片存储路径
filePathConstan:
  remoteImageRootPath: /wapp/jxfp/image/
  remoteCostFileRootPath: /wapp/jxfp/cost/
  remoteKnowFileRootPath: /wapp/jxfp/knowCenter/
  remoteAnnouncementRootPath: /wapp/jxfp/announcement/
  remoteQuestionPaperFileRootPath: /wapp/jxfp/question/
  remoteQuestionPaperFileTempRootPath: /wapp/jxfp/temp/question/
  remoteCostFileTempRootPath: /wapp/jxfp/temp/cost/
  remoteExcelFileRootPath: /wapp/jxfp/excel/
  remoteFixedRootPath: /wapp/jxfp/fixed/ #供应商红票remoteFixedRootPath
  remoteFixedTempRootPath: /wapp/jxfp/temp/fixed/ #供应商红票远程文件临时存放路径
  localImageRootPath: /wapp/jxfp/image/
  tempPath: /wapp/jxfp/temp/zip/      # 文件暂存路径
  depositPath: /wapp/jxfp/zipto/ # 文件存储路
  tempImgPath: /wapp/jxfp/temp/imgzip/      # 图片临时存储路径
  signInImgPath: /wapp/jxfp/temp/image/     #扫码签收图片暂存路径
  tempDir: /wapp/jxfp/temp/excelZip/
  sapRemoteRootPath: /wapp/jxfp/sap/source/   #sap源文件目录
  sapRemoteBakPath: /wapp/jxfp/sap/bak/       #sap备份目录
  sapLocalTempPath: /wapp/jxfp/sap/temp/         #sap本地临时目录
  aribatempPath: /wapp/jxfp/temp/zip/      # 文件暂存路径
  aribadepositPath: /wapp/jxfp/zipto/ # 文件存储路
  erweimaPath: /wapp/jxfp/QRCode/image/
  orderSapRemoteRootPath: /wapp/jxfp/order/sap/source/   #sap源文件目录（订单获取）
  orderSapRemoteBakPath: /wapp/jxfp/order/sap/bak/       #sap备份目录（订单获取）
  orderSapLocalTempPath: /wapp/jxfp/order/sap/temp/
  vendorRemoteRootPath: /wapp/jxfp/vendor/source/   #vendor源文件目录(导入10位供应商号)
  vendorRemoteBakPath: /wapp/jxfp/vendor/bak/       #vendor备份目录
  vendorLocalTempPath: /wapp/jxfp/vendor/temp/         #vendor本地临时目录
  localFixedRootPath: /wapp/jxfp/fixed/temp/ #供应商红票本地文件存放路径
  sso: d:/sso/sso.txt
    
#定时删除原始数据
del-origin-data-timer:
  open: true
  beforeDays: 2
  handle-cron: 0 0 12 * * ?

#riverSand定时任务
riverSand:
  synchro-cron: 0 0 0/3 * * ?
  latestTime: 2011-11-11 11:11:11
host:
  synchro-cron: 0 16 3 * * 1
  login-name: gf001,gf002
  
#####chc 限制红字开票税盘
taxNo:
  terminal: '{"914403007109368585":"RCNFMZ4U,BQFHFLGG,IH9HPG12"}'


  
###BMS配置信息
bms:
  feedback:
    # 加密秘钥
    appSecret: 9039965DEA73EF189935D9044EC08AC6
    # bms验真结果反馈
    bmsVerifyFeedbackUrl: https://mdc-qa-aloha-gateway.cn.wal-mart.com/bms-cost/wapp/in/feedback/invoice
    bmsTaxBillFeedbackUrl: https://mdc-qa-aloha-gateway.cn.wal-mart.com/bms-cost/wapp/in/feedback/taxBill
    bmsQueryTaxBillUrl: https://mdc-qa-aloha-gateway.cn.wal-mart.com/bms-cost/wapp/in/queryTaxBill
    bmsInvoiceReceiptUrl: https://mdc-qa-aloha-gateway.cn.wal-mart.com/bms-cost/wapp/in/feedback/invoiceReceipt
