wapp:
  integration:
    authentication: walmart-wapp-fat20211014092441131056839
    client-id: T3950544920211014092441131056783
    customer-no: T3950544920211014092441131056783
    tenant-id: 4882809030005538709
    tenant-code: Walmart
    tenant-name: Walmart
    action:
      # ofd解析 验签
      ofd: 0FBBB88B01E6EF8E84641AFA3521965F
      # 发票验真
      verification: E988114EC83E2C1FBA93F180B8D68CD8
      # 申请红字信息表
      rednotification: A9F0665B2C933F31D5145B7A1CC571EB
      # 获取终端
      terminals: A9F0665B2C933F31D5145B7A1CC571EB
      # 红字信息撤销
      rollback: E52D6CD30701F28988FBA92E1459AD45
      # 红字信息生成pdf
      genredpdf: 663133D11FC88FC56BA3585258005260
      #识别
      discern: 2C528F63F591A73C65007B9C16CF6E6F
      discern-callbackUrl: inte-janus.melete
    host:
      tcp: janus-tcp-inte.xforceplus.com
      http: https://janus-inte.xforceplus.com:443
    port:
      tcp: 443
  db2:
    base-url: 127.0.0.1
  export_success_queue_gfone: cn.wm.host.export.success.queue.gfone
  export:
    tmp: /tmp/excel
activemq:
  queue-name:
    export-request: fat-cn.wm.host.enhance.export-request.queue # 导出申请
    enhance-claim-verdict-queue: fat-cn.wm.host.enhance.claim.verdict.queue #索赔单不定案逻辑处理
taxRateSet: 0.13,0.11,0.09,0.06,0.05,0.03,0.01,0.00
spring:
  redis:
    host: wapp-redis
server:
  port: 6060


#图片存储路径
filePathConstan:
  remoteImageRootPath: /home/wappftp/jxfp/image/
  remoteCostFileRootPath: /home/wappftp/jxfp/cost/
  remoteKnowFileRootPath: /home/wappftp/jxfp/knowCenter/
  remoteAnnouncementRootPath: /home/wappftp/jxfp/announcement/
  remoteQuestionPaperFileRootPath: /home/wappftp/jxfp/question/
  remoteQuestionPaperFileTempRootPath: /home/wappftp/jxfp/temp/question/
  remoteCostFileTempRootPath: /home/wappftp/jxfp/temp/cost/
  remoteExcelFileRootPath: /home/wappftp/wapp/excel/
  remoteFixedRootPath: /jxfp/fixed/ #供应商红票remoteFixedRootPath
  remoteFixedTempRootPath: /jxfp/temp/fixed/ #供应商红票远程文件临时存放路径
  localImageRootPath: /home/vn03qsx/jxfp/image/
  tempPath: /home/wappftp/jxfp/temp/zip/      # 文件暂存路径
  depositPath: /home/wappftp/jxfp/zipto/ # 文件存储路
  tempImgPath: /home/wappftp/jxfp/temp/imgzip/      # 图片临时存储路径
  signInImgPath: /home/wappftp/jxfp/temp/image/     #扫码签收图片暂存路径
  tempDir: /home/wappftp/jxfp/temp/excelZip/
  sapRemoteRootPath: /jxfp/sap/source/   #sap源文件目录
  sapRemoteBakPath: /jxfp/sap/bak/       #sap备份目录
  sapLocalTempPath: /home/wappftp/jxfp/sap/temp/         #sap本地临时目录
  aribatempPath: /usr/users/dxhy152/wapp/jxfp/temp/zip/      # 文件暂存路径
  aribadepositPath: /usr/users/dxhy152/wapp/jxfp/zipto/ # 文件存储路
  erweimaPath: /usr/users/dxhy152/wapp/jxfp/QRCode/image/
  orderSapRemoteRootPath: /jxfp/order/sap/source/   #sap源文件目录（订单获取）
  orderSapRemoteBakPath: /jxfp/order/sap/bak/       #sap备份目录（订单获取）
  orderSapLocalTempPath: /usr/users/dxhy152/wapp/jxfp/order/sap/temp/
  vendorRemoteRootPath: /jxfp/vendor/source/   #vendor源文件目录(导入10位供应商号)
  vendorRemoteBakPath: /jxfp/vendor/bak/       #vendor备份目录
  vendorLocalTempPath: /usr/users/dxhy152/wapp/jxfp/vendor/temp/         #vendor本地临时目录
  localFixedRootPath: /usr/users/dxhy152/wapp/jxfp/fixed/temp/ #供应商红票本地文件存放路径
  sso: d:/sso/sso.txt


#sftp配置
pro:
  sftp:
    host: 10.100.2.16  #10.44.100.123
    username: wappftp
    password: testwapp123
    # 授权方式：公私钥和密码选择一个，测试时选择密码
    auth-method: password
    default:
      port: 22
      timeout: 60000
      privateKey: /home/wappftp/.ssh/id_rsa
      passphrase:
