wapp:
  bill:
    export:
      limit: 1000000
  integration:
    authentication: walmart-wapp-fat20211014092441131056839
    client-id: T3950544920211014092441131056783
    customer-no: T3950544920211014092441131056783
    tenant-id: 5793722992790675456
    tenant-code: Walmart
    tenant-name: Walmart
    action:
      verification-xml: xx
      sync-tax-code: xx
      # ofd解析 验签
      ofd: 0FBBB88B01E6EF8E84641AFA3521965F
      # 发票验真
      verification: E988114EC83E2C1FBA93F180B8D68CD8
      # 申请红字信息表
      rednotification: C6D28535F2ADE4D5DB655AE71D87375A
      # 获取终端
      terminals: A9F0665B2C933F31D5145B7A1CC571EB
      splitInvoice: 9449D82ECF3D2712E47A489F491A19BD
      # 红字信息撤销
      rollback: E52D6CD30701F28988FBA92E1459AD45
      # 红字信息生成pdf
      genredpdf: 663133D11FC88FC56BA3585258005260
      #识别
      discern: 2C528F63F591A73C65007B9C16CF6E6F
      discern-callbackUrl: inte-janus.melete
      #下载附件
      downLoadAction: A9EC3ACD57C452AE933AE67B42E452E2
      # 税编查询
      tax-code: 88783DD6EF9484C5DB5EE795A0E920C1
      #上传3.0平台 税编
      send-tax-code: 77BC9129AC33F3F83DD73F2767BF2EF4
    host:
      tcp: janus-tcp-inte-tx.xforceplus.comxxx
      http: https://janus-inte-txxxx.xforceplus.com:443
    sign:
      splitInvoice: 0618de7ca5a54e44b85293cc7929312e
      tax-code: 9afc34ea775683aa44fc1787da9bbeaf
      send-tax-code: 0618de7ca5a54e44b85293cc7929312e
    port:
      tcp: 443
    # riversand的税编同步接口地址-生产
    riversand:
      url: http://esb-qa.cn.wal-mart.com/ssp-item-oe/riversand/export/v1/page/info
  host:
    base-url: https://aloha-qa.walmartmobile.cn
    find-by-nbrs-url: /item-oe/findByNbrs
    app-name: chc-fapiao
    app-access-token: 70F7DAEB1555DE8DC9D47746ABF22195
  export_success_queue_gfone: cn.wm.host.export.success.queue.gfone
  export:
    tmp: /tmp/excel
  rednotification:
    maxApply: 50
activemq:
  queue-name:
    export-request: fat-cn.wm.host.enhance.export-request.queue # 导出申请
    enhance-claim-verdict-queue: fat-cn.wm.host.enhance.claim.verdict.queue #索赔单不定案逻辑处理
    export-success-queue-gfone: cn.wm.host.export.success.queue.gfone
    deduct-notification: fat-cn.wm.host.enhance.deduct.notification.queue
    import-riversand-taxcode-queue: import.riverand.taxcode.queque #riversand税编导入比较逻辑处理
taxRateSet: 0.13,0.11,0.09,0.06,0.05,0.03,0.01,0.00
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
  datasource:
    url: jdbc:p6spy:sqlserver://10.100.20.5:1433;DatabaseName=testdb01
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    username: testuser01
    password: aGSsdsJFWd_w_1
    hikari:
      minimum-idle: 30
      maximum-pool-size: 100
  activemq:
    broker-url: tcp://127.0.0.1:61616
#    broker-url: tcp://10.100.2.17:61616
    user: admin
    password: admin
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
server:
  port: 6060

springfox:
  documentation:
    swagger-ui:
      base-url: /enhance-swagger
    swagger:
      v2:
        path: /enhance-swagger/v2/api-docs

#图片存储路径
filePathConstan:
  remoteImageRootPath: /home/wappftp/jxfp/image/
  remoteCostFileRootPath: /home/wappftp/jxfp/cost/
  remoteKnowFileRootPath: /home/wappftp/jxfp/knowCenter/
  remoteAnnouncementRootPath: /home/wappftp/jxfp/announcement/
  remoteQuestionPaperFileRootPath: /home/wappftp/jxfp/question/
  remoteQuestionPaperFileTempRootPath: /home/wappftp/jxfp/temp/question/
  remoteCostFileTempRootPath: /home/wappftp/jxfp/temp/cost/
  remoteExcelFileRootPath: /home/wappftp/wapp/excel/
  remoteFixedRootPath: /jxfp/fixed/ #供应商红票remoteFixedRootPath
  remoteFixedTempRootPath: /jxfp/temp/fixed/ #供应商红票远程文件临时存放路径
  localImageRootPath: /home/vn03qsx/jxfp/image/
  tempPath: /home/wappftp/jxfp/temp/zip/      # 文件暂存路径
  depositPath: /home/wappftp/jxfp/zipto/ # 文件存储路
  tempImgPath: /home/wappftp/jxfp/temp/imgzip/      # 图片临时存储路径
  signInImgPath: /home/wappftp/jxfp/temp/image/     #扫码签收图片暂存路径
  tempDir: /home/wappftp/jxfp/temp/excelZip/
  sapRemoteRootPath: /jxfp/sap/source/   #sap源文件目录
  sapRemoteBakPath: /jxfp/sap/bak/       #sap备份目录
  sapLocalTempPath: /home/wappftp/jxfp/sap/temp/         #sap本地临时目录
  aribatempPath: /usr/users/dxhy152/wapp/jxfp/temp/zip/      # 文件暂存路径
  aribadepositPath: /usr/users/dxhy152/wapp/jxfp/zipto/ # 文件存储路
  erweimaPath: /usr/users/dxhy152/wapp/jxfp/QRCode/image/
  orderSapRemoteRootPath: /jxfp/order/sap/source/   #sap源文件目录（订单获取）
  orderSapRemoteBakPath: /jxfp/order/sap/bak/       #sap备份目录（订单获取）
  orderSapLocalTempPath: /usr/users/dxhy152/wapp/jxfp/order/sap/temp/
  vendorRemoteRootPath: /jxfp/vendor/source/   #vendor源文件目录(导入10位供应商号)
  vendorRemoteBakPath: /jxfp/vendor/bak/       #vendor备份目录
  vendorLocalTempPath: /usr/users/dxhy152/wapp/jxfp/vendor/temp/         #vendor本地临时目录
  localFixedRootPath: /usr/users/dxhy152/wapp/jxfp/fixed/temp/ #供应商红票本地文件存放路径
  sso: d:/sso/sso.txt


#sftp配置
pro:
  sftp:
#    host: 10.100.2.17  #10.44.100.123
    host: 172.18.211.69
    username: wappftp
    password: testwapp123
    # 授权方式：公私钥和密码选择一个，测试时选择密码,pwd密码，private 私钥，默认private
    auth-method: pwd
    default:
      port: 22
      timeout: 60000
      privateKey: /home/wappftp/.ssh/id_rsa
      passphrase:

#定时删除原始数据
del-origin-data-timer:
  open: true
  beforeDays: 2
  handle-cron: 0 0 12 * * ?
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.xforceplus.wapp.repository.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl