wapp:
  integration:
    authentication: Walmart-wapp-enhance-dev2021101114111213460599
    client-id: T395054492021101114111213460567
    customer-no: T395054492021101114111213460567
    tenant-id: 4882809030005538709
    tenant-code: Walmart
    tenant-name: Walmart
    action:
      # ofd解析 验签
      ofd: 0E707DB76E9B55CA069263CE911E36A5
      # 发票验真
      verification: 3A0ED452A8386C3B04B1F9C3F6C76A42
      # 申请红字信息表
      rednotification: FECD0B7724B239B3C5950FDBDB1D09E0
      # 获取终端
      terminals: 816A43875B12DE4B50EBEC29E4DA56E2
      # 红字信息撤销
      rollback: 8F8D2FFCA3F768BB2D7A4D7634BB7274
      # 红字信息生成pdf
      genredpdf: E96F0AB61D35F93BF48928D568A97C5B
      #识别
      discern: 043F1FF00631D5E8F0261CD532D2F477
      discern-callbackUrl: inte-janus.melete
    host:
      tcp: janus-tcp-inte.xforceplus.com
      http: https://janus-inte.xforceplus.com
    port:
      tcp: 443
  db2:
    base-url: 127.0.0.1
  export_success_queue_gfone: cn.wm.host.export.success.queue.gfone

taxRateSet: 0.13,0.11,0.09,0.06,0.05,0.03,0.01,0.00
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


