server:
  port: 8080
spring:
  redis:
    cluster:
      nodes: pose-redis-app-51126a-pdc.cn.wal-mart.com:6379,pose-redis-app-51126b-pdc.cn.wal-mart.com:6379,pose-redis-app-51126c-pdc.cn.wal-mart.com:6379,pose-redis-app-51126d-mdc.cn.wal-mart.com:6379,pose-redis-app-51126e-mdc.cn.wal-mart.com:6379,pose-redis-app-51126f-mdc.cn.wal-mart.com:6379
    password: bIgSd!NE68duk#fRo
    port: 6379
    lettuce:
      pool:
        max-idle: 16
        max-action: 32
        min-idle: 8
  datasource:
    druid:
      url: jdbc:sqlserver://pcnnt57090sql.cn.wal-mart.com:14481;DatabaseName=WAPP
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      username: svcwappdb
      password: QaNn^RWjEy58iYXN
      initial-size: 10
      max-active: 1000
      min-idle: 100
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      # testOnBorrow和testOnReturn在生产环境一般是不开启的，主要是性能考虑。失效连接主要通过testWhileIdle保证
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: false
        url-pattern: /druid/*
        login-username: admin
        login-password: admin456123
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
          enabled: true
        wall:
          config:
            multi-statement-allow: true
  activemq:
    broker-url: failover:(tcp://161.163.18.68:61616)?randomize=false&jms.useAsyncSend=true&jms.sendTimeout=3000
    user: admin
    password: admin

# 税款所属期判断值
currentTaxPeriod: 15

# 注意事项, 上传到SFTP的数据请按照以下模板填充数据，要求
# 1、文件名可用由用户自己定义（务必全局唯一，对于重名的文件一律不处理）
# 2、电子表格名称如果需要自定义请通知研发配置（不需要发版）
# 3、电子表格表头（第一行）不允许变更，如果一定要变更请提前通知研发调整代码，重新发版
# 4、同一批单据和明细请按照模板格式统一存储到同一个excel的不同sheet中
# 5、SFTP路径定义如下
agreementBill:
  scan-cron: 0 0 4 * * ?
  parse-cron: 0 0 5 * * ?
  remote:
# 协议单SFTP远程目录
    path: /home/wapp/vendor/agreement
  local:
    path: /tmp/wapp/vendor/agreement
  sheetName: fbl5n
  item:
    sheetName: zarr
claimBill:
  scan-cron: 0 0 22 * * ?
  parse-cron: 0 0 0 * * ?
  diff-amount-rate: -1
  remote:
# 索赔单及明细SFTP远程目录
    path: /home/wapp/vendor/claim
  local:
    path: /tmp/wapp/vendor/claim
  sheetName: claim
  item:
    hyperSheetName: hyper
    samsSheetName: sams
epdBill:
  scan-cron: 0 30 4 * * ?
  parse-cron: 0 30 5 * * ?
  remote:
# EPD单及LOG明细SFTP远程目录
    path: /home/wapp/vendor/epd
  local:
    path: /tmp/wapp/vendor/epd
  sheetName: epd
  item:
    sheetName: log
 
####索赔协议定时任务   
task: 
  AgreementDeductScheduler-cron: 0 0 4 * * ?
  ClaimBlueInvoiceScheduler-cron: 0 0 1 * * ?
  ClaimDeductScheduler-cron: 0 0 1 * * ?
  ClaimDeductTaxCodeScheduler-cron: 0 0 12 * * ?
  ClaimSettlementScheduler-cron:  0 0 3 * * ?
  EPDDeductScheduler-cron: 0 0 5 * * ?
  SettlementOverDueScheduler-cron: 0 0 1 * * ?
  SettlementScheduler-cron: 0 0 6 * * ?
  SettlementTaxCodeScheduler-cron: 0 0 20 * * ?
  blueInvoiceAutoAuth-cron: 0 0 1 * * ?
  RedNotificationScheduler-cron: 0 10/10 * * * ?
  RedNotificationAutoApplyScheduler-cron: 0 0/5 * * * ?
  SysLogClearExpireScheduler-cron: 0 0 2 * * ?
  customerBMS-cron: 0 0/10 * * * ?
  InvoiceReceiptBMS-cron: 0 0/30 * * * ?
 
####################
#integration 集成平台相关配置
#################### 
wapp:
  integration:
    authentication: walmart-red20211130094319792199387
    client-id: T3950544920211130094319792199357
    customer-no: T3950544920211130094319792199357
    tenant-id: 5938770886372409344
    tenant-code: Walmart
    tenant-name: Walmart
    action:
      # ofd解析 验签
      ofd: D632AA5AC056788525147AD0A4D843F1
      # 发票验真
      verification: 6AE0C78D3E561474334A25EE8CC4020F
      # 申请红字信息表
      rednotification: 82152984CC74EE4E87B8D965F8A72808
      # 获取终端
      terminals: BC81277C3F8B1E26DD227838486BCA04
      splitInvoice: 723EA9FE0EBB4FFA589D86DD2B512741
      # 红字信息撤销
      rollback: E041B9B1D025D63A2B7E78033694205A
      # 红字信息生成pdf
      genredpdf: 9F98620DEB4889598D6EF6FE02E0D70F
      #识别
      discern: F4679DBC6755820AB12AB7AAB05D0E5B
      discern-callbackUrl: prod-janus.melete
      #下载附件
      downLoadAction: 7A9D0DE54A30B9E985120BAC8F42C09B
      # 税编查询
      tax-code: 7C0E7F8E1BCF4B31BA00603CBAE391AB
      #上传3.0平台 税编
      send-tax-code: F52023832D8973826C8972FB245F99A4
      #税编同步更新到3.0平台
      sync-tax-code: F52023832D8973826C8972FB245F99A4
      #XML解析
      verification-xml: 555228790DBA98735A8996828C8552B4
    host:
      tcp: janus-tcp-tx.xforceplus.com
      http: https://janus-tx.xforceplus.com:443
    sign:
      splitInvoice: 44aaabcd484a18c5bff669d8a8b62200
      tax-code: 44aaabcd484a18c5bff669d8a8b62200
      send-tax-code: 44aaabcd484a18c5bff669d8a8b62200
    port:
      tcp: 443
    # riversand的税编同步接口地址-生产
    riversand:
      url: https://aloha.cn.wal-mart.com/ssp-item-oe/riversand/export/v1/page/info
  db2:
    base-url: http://esb.cn.wal-mart.com
  export:
    tmp: /tmp/excel
  rednotification:
    maxApply: 50
  host:
    base-url: https://aloha.cn.wal-mart.com
    c-name: wapp-evat
    app-name: chc-fapiao
    app-access-token: 70F7DAEB1555DE8DC9D47746ABF22195
    bufferSize: 4
    # riversand的税编同步接口地址-生产
    tax-code-url: /item-oe/riversand/export/v1/page/info
    hyper-nbrs-url: /item-oe/riversand/export/v1/info
    sams-nbrs-url: /item-oe/db2Direct/findByUpcNumbers
  history-data:
    time: 2022-10-31 17:00:00   
  tax-rate: 0.00,0.01,0.03,0.06,0.09,0.10,0.11,0.13,0.16,0.17
  nas:
    url: /u/app/evtaSystemIntegration/wapp
    
#ESB    
Esb:
  url:
    upload: http://10.100.2.17:8083/object/upload
    downLoad: http://10.100.2.17:8083/object/downLoad/   
##
##
##消息队列相关配置
activemq:
  queue-name:
    export-request: cn.wm.host.enhance.export-request.queue # 导出申请
    enhance-claim-verdict-queue: cn.wm.host.enhance.claim.verdict.queue #索赔单不定案逻辑处理
    export-success-queue-gfone: cn.wm.host.export.success.queue.gfone
    deduct-notification: cn.wm.host.enhance.deduct.notification.queue
    import-riversand-taxcode-queue: import.riverand.taxcode.queque #riversand税编导入比较逻辑处理
taxRateSet: 0.13,0.11,0.09,0.06,0.05,0.03,0.01,0.00

####sftp配置
pro:
  sftp:
    host: CNFSAPP06.CN.Wal-Mart.com  #10.44.100.123
    username: SVCwappvm
    password: Dxhy@2019!
    # 授权方式：公私钥和密码选择一个，测试时选择密码,pwd密码，private 私钥，默认private
    auth-method: private
    default:
      port: 22
      timeout: 60000
      privateKey: /u/app/ssh/id_rsa
      passphrase:
#
#SFTP 定义路径
#图片存储路径
filePathConstan:
  remoteImageRootPath: /home/wapp/jxfp/image/
  remoteCostFileRootPath: /home/wapp/jxfp/cost/
  remoteKnowFileRootPath: /home/wapp/jxfp/knowCenter/
  remoteAnnouncementRootPath: /home/wapp/jxfp/announcement/
  remoteQuestionPaperFileRootPath: /home/wapp/jxfp/question/
  remoteQuestionPaperFileTempRootPath: /home/wapp/jxfp/temp/question/
  remoteCostFileTempRootPath: /home/wapp/jxfp/temp/cost/
  remoteExcelFileRootPath: /home/wapp/wapp/excel/
  remoteFixedRootPath: /jxfp/fixed/ #供应商红票remoteFixedRootPath
  remoteFixedTempRootPath: /jxfp/temp/fixed/ #供应商红票远程文件临时存放路径
  localImageRootPath: /home/vn03qsx/jxfp/image/
  tempPath: /home/wapp/jxfp/temp/zip/      # 文件暂存路径
  depositPath: /home/wapp/jxfp/zipto/ # 文件存储路
  tempImgPath: /home/wapp/jxfp/temp/imgzip/      # 图片临时存储路径
  signInImgPath: /home/wapp/jxfp/temp/image/     #扫码签收图片暂存路径
  tempDir: /home/wapp/jxfp/temp/excelZip/
  sapRemoteRootPath: /jxfp/sap/source/   #sap源文件目录
  sapRemoteBakPath: /jxfp/sap/bak/       #sap备份目录
  sapLocalTempPath: /home/wapp/jxfp/sap/temp/         #sap本地临时目录
  aribatempPath: /usr/users/dxhy152/wapp/jxfp/temp/zip/      # 文件暂存路径
  aribadepositPath: /usr/users/dxhy152/wapp/jxfp/zipto/ # 文件存储路
  erweimaPath: /usr/users/dxhy152/wapp/jxfp/QRCode/image/
  orderSapRemoteRootPath: /jxfp/order/sap/source/   #sap源文件目录（订单获取）
  orderSapRemoteBakPath: /jxfp/order/sap/bak/       #sap备份目录（订单获取）
  orderSapLocalTempPath: /usr/users/dxhy152/wapp/jxfp/order/sap/temp/
  vendorRemoteRootPath: /jxfp/vendor/source/   #vendor源文件目录(导入10位供应商号)
  vendorRemoteBakPath: /jxfp/vendor/bak/       #vendor备份目录
  vendorLocalTempPath: /usr/users/dxhy152/wapp/jxfp/vendor/temp/         #vendor本地临时目录
  localFixedRootPath: /usr/users/dxhy152/wapp/jxfp/fixed/temp/ #供应商红票本地文件存放路径
  sso: d:/sso/sso.txt


#定时删除原始数据
del-origin-data-timer:
  open: true
  beforeDays: 2
  handle-cron: 0 0 12 * * ?
  
#riverSand定时任务
riverSand:
  synchro-cron: 0 0 5 * 11 7
  latestTime: 2015-01-01 00:00:00
host:
  synchro-cron: 0 16 3 * * 1
  login-name: gf001,gf002,j0j0h4w,l5feng,m0w0aus,s0c07id,vdeng,vn52fx3,a0p00ug
  
#####chc 限制红字开票税盘
taxNo:
  terminal: '{"914403007109368585":"RCNFMZ4U,BQFHFLGG,IH9HPG12"}'

###BMS配置信息
bms:
  feedback:
    # 加密秘钥
    appSecret: 9039965DEA73EF189935D9044EC08AC6
    # bms验真结果反馈
    bmsVerifyFeedbackUrl: https://mdc-qa-aloha-gateway.cn.wal-mart.com/bms-cost/wapp/in/feedback/invoice
    bmsTaxBillFeedbackUrl: https://mdc-qa-aloha-gateway.cn.wal-mart.com/bms-cost/wapp/in/feedback/taxBill
    bmsQueryTaxBillUrl: https://mdc-qa-aloha-gateway.cn.wal-mart.com/bms-cost/wapp/in/queryTaxBill
    bmsInvoiceReceiptUrl: https://mdc-qa-aloha-gateway.cn.wal-mart.com/bms-cost/wapp/in/feedback/invoiceReceipt
